### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by Saloed** [Mika1212/HomeTar#1]
1. Тестовые примеры лучше положить в какую-то директорию, например `testData`, чтобы они не замусоривали проект
2. Функция [`isEqual` ](https://github.com/Mika1212/HomeTar/blob/07ccec7ae4db3fdf5a72557ccd691abf42fde19d/src/main/java/HomeTar.java#L126) нужна только для тестов, так что лучше разместить её в тестах 
3. Чтобы указать код символа, лучше использовать символ в одинарных кавычках [link](https://github.com/Mika1212/HomeTar/blob/07ccec7ae4db3fdf5a72557ccd691abf42fde19d/src/main/java/HomeTar.java#L134)
4. Не очень понятно, почему при сравнении файлов некоторые символы нужно пропускать. [link](https://github.com/Mika1212/HomeTar/blob/07ccec7ae4db3fdf5a72557ccd691abf42fde19d/src/main/java/HomeTar.java#L134)
5. Замечания по парсингу аргументов:
     - Обращаться в к аргументам по индексу без проверки, что такой индекс там есть, это нехорошо. Полетит исключение, которое ничего не скажет пользователю вашей утилиты. 
     - Не хватает какого-то `help` сообщения, чтобы не заглядывая в код можно было понять, что там ваша утилита умеет и какие флаги у неё есть.
     - Кусок парсинга в main, а кусок где-то в другой функции
     - Если не хотите вот этим всем заниматься, то можете использовать готовую библиотеку (например, [commons-cli](https://commons.apache.org/proper/commons-cli/))
6. А [вот это](https://github.com/Mika1212/HomeTar/blob/07ccec7ae4db3fdf5a72557ccd691abf42fde19d/src/main/java/HomeTar.java#L120) зачем? 
7. А почему `int`, а не `char`? [link](https://github.com/Mika1212/HomeTar/blob/07ccec7ae4db3fdf5a72557ccd691abf42fde19d/src/main/java/HomeTar.java#L21)
8. В Java принято указывать наименее специфичный тип. В данном случае, слева лучше написать просто `List<String>`. [link](https://github.com/Mika1212/HomeTar/blob/07ccec7ae4db3fdf5a72557ccd691abf42fde19d/src/main/java/HomeTar.java#L23)
9. В тестах наверное хотелось бы видеть что-то вроде: вот есть куча файлов, мы их слепили в один файл, потом разлепили опять на кучу файлов и проверили, что все файлы из входной кучи совпадают с файлами из выходной

**Comment by Mika1212** [comment]
Сделано

**Comment by Saloed** [comment]
1. Запихнуть всё в одну функцию это тоже нехорошо. Так очень сложно разбираться что и где происходит. Лучше сначала распарсить все аргументы, а потом вызывать функции, которые что-то делают.
2. Заранее заготовленные файлы с копией это не очень наглядно. Хотелось бы увидеть какой-то такой процесс:
   - Исходные файлы копируются средствами стандартной библиотеки. [Вот так.](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#copy-java.nio.file.Path-java.nio.file.Path-java.nio.file.CopyOption...-)
   - Копии собираются в один файл утилитой
   - Копии удаляются [вот так](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#delete-java.nio.file.Path-)
   - Единый файл распаковывается обратно
   - Проверяется соответствие исходных файлов и того, что распаковалось
3. При сравнении файлов, если левый закончился раньше правого, то он скажет, что они равны. Это не хорошо. 
4. Лучше всего при сравнении файлов просто вычитать оба [через вот это](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#readAllBytes(java.nio.file.Path)), а потом сделать `assertArrayEquals` или просто `Arrays.equals`. Чем сложнее реализовано сравнение в тестах, тем больше вероятность, что там кто-то накосячил и соответственно меньше доверия к такому сравнению. 
5. При работе с файлами, лучше везде использовать не `File`, а `Path`. Получить его можно через [Paths.get](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Paths.html#get(java.lang.String,%20java.lang.String...))

**Comment by Saloed** [comment]
1. Ловим assert, чтобы вернуть boolean, чтобы потом кинуть assert. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/test/java/HomeTarTest.java#L41)
2. В Junit есть аннотации `@BeforeEach` и `@AfterEach`. Они позволяют указать, что какую-то функцию нужно выполнять перед и после каждого теста соответственно. Лучше использовать их. 
3. При распаковке у вас tar создаст файлы с такими же именами, как и исходные. То есть сейчас самые исходные тестовые данные перезаписываются. Это не очень хорошо. К тому же, перед распаковкой файлы, которые туда были упакованы, не удаляются. Лучше упаковывать копии исходных файлов, их удалять, распаковывать и сравниваться с исходными файлами. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/test/java/HomeTarTest.java#L65)
4. А почему здесь просто `Path` не принимать? [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/test/java/HomeTarTest.java#L35)
5. Где проверка, что там такой индекс есть? `hometar -u` просто упадёт. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L34)
6. Добавить в список, чтобы тут же достать из списка это что-то странное, при учёте того, что список нигде больше не используется [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L34)
7. IndexOutOfBounds [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L39)
8. `hometar -out res a.txt b.txt` это валидно. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L40)
9. В таком случае, лучше человеку help вывести, как и при любой другой ошибке с аргументами. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L45)
10. Замечание 7 из первого списка
11. `C:\Program Files\xxx.txt` будет очень рад вашему способу определения конца имени файла. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L69)
12. IndexOutOfBounds? [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L82)
13. Лучше `Files.exists`. [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L105)
14. `writer.toString()` [link](https://github.com/Mika1212/HomeTar/blob/ee58abbe6c0ffcda1ca3624b7329ef77c89abecd/src/main/java/HomeTar.java#L133)

**Comment by Mika1212** [comment]
@Saloed 
3) Не получилось поменять на копии, т.к. с ними из-за чего-то опять начала появляться ошибка "процесс не может получить доступ к файлу...". Решить ее не получилось, хотя я вроде бы все fileWriter'ы закрываю (есть переделанный под копии файл с тестами - одна из предыдущих версий)
11) К сожалению, не очень понял, в чем проблема: у меня в output'e будет запись вида "C:\Program Files\xxx.txt xxx(кол-во символов)" и как раз таки этот пробел я и ищу

**Comment by Saloed** [comment]
11. Я имел ввиду, что имя файла может содержать пробелы. Я просто почему-то показалось, что вы абсолютный путь сохраняете. Давайте тогда новый пример: `New Text Document.txt`.
3. У вас в проекте есть баг. Вы открываете больше writerов чем закрываете. Я сейчас склонил ваш проект, поправил одну строчку и всё заработало. Предлагаю вам сделать также.

**Comment by Mika1212** [comment]
@Saloed 
Готово

**Comment by Saloed** [comment]
1. Опять парсинг аргументов. Я уверен, что там есть места, в которых полетит IndexOutOfBounds. Посмотрите внимательнее. 
2. Кажется, у вас проверка на количество аргументов не позволяет запаковать 1 файл. Это странно.
3. Если у вас в архиве не нашлось имени файла, то это не ошибка в аргументах. Это какой-то неправильный архив вам подсунули. Нужно выдавать соответствующую ошибку. 
4. Сделайте какой-то более универсальный подход к хранению имени файла. `|` зарезервирован под имена служебных файлов только в Windows (NTFS, Fat). В Unix системах типа MacOS или Linux `|`  может встречаться в имени файла https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations
5. По поводу того, как вы вычисляете длину текста. `FileReader` и его `read` привязаны к кодировке, которая у ни задана. В различных кодировках размер одного символа разный. Например, в `UTF-8` размер 1 символа 1 байт, а в `UTF-16` 2 байта. Так что, если вы работает с символами, то кодировку нужно задать явно, иначе, если запаковать файлы на JVM, у которой по умолчанию `UTF-8`, а распаковать на JVM, у которой по умолчанию `UTF-16`, то результат получится очень странным.

**Comment by Mika1212** [comment]
На счет кодировки: я попробовал переделать через UTF_8.hashCode(), можно ли так делать? Сделать вот так 
" FileReader reader = new FileReader(s, UTF_8); " не получилось, вылезает ошибка, которую я не смог решить 
За теги прошу прощения, я подумал, это будет удобнее чем через мессенджер

**Comment by Saloed** [comment]
`UTF_8.hashCode()` не очень понятно при чём тут `hashCode`. 

А что за ошибка вылезает?

**Comment by Saloed** [comment]
Проще всего создать `BufferedReader` с нужным `Charset` используя функцию [`Files.newBufferedReader`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#newBufferedReader-java.nio.file.Path-java.nio.charset.Charset-)

**Comment by Mika1212** [comment]
Переделал

Сама ошибка: 
java: no suitable constructor found for FileReader(java.lang.String,java.nio.charset.Charset)
    constructor java.io.FileReader.FileReader(java.lang.String) is not applicable
      (actual and formal argument lists differ in length)
    constructor java.io.FileReader.FileReader(java.io.File) is not applicable
      (actual and formal argument lists differ in length)
    constructor java.io.FileReader.FileReader(java.io.FileDescriptor) is not applicable
      (actual and formal argument lists differ in length)

![Screenshot_5](https://user-images.githubusercontent.com/54846851/111300357-0db7d300-8662-11eb-98e8-fe7fe97b7e0b.png)

**Comment by Saloed** [comment]
1. Парсинг всё ещё работает плохо.
![image](https://user-images.githubusercontent.com/8640896/111303022-19f15f80-8665-11eb-89d4-59d5442847cb.png)
![image](https://user-images.githubusercontent.com/8640896/111303276-6341af00-8665-11eb-8ea4-0649d11f164f.png)
2. Если вы записываете архив в `UTF-8`, то и читать его нужно в той же кодировке

**Comment by Mika1212** [comment]
Вроде бы все исправил

**Comment by Saloed** [comment]
Я так понимаю, файл лучше не называть например `my-user-data.txt`, а то в нём будет `-u` и всё сломается

**Comment by Mika1212** [comment]
Да, вы правильно подметили. Я думаю все таки проверки на двойные(или больше) ключи можно убрать, т.к. они все равно выскочат как ошибки не найденных файлов. Теперь и с таким, и с таким: "my-out-user-data.txt" названием заработает

**Comment by Saloed** [comment]
Да, кодировку всегда лучше указывать явно. 

1. Вот тут лучше не исключение кидать, а сделать просто `return` или `System.exit`. Обычно, если из приложения наружу летит исключение, то это значит, что у него внутри что-то сломалось. А тут вроде нормальная обработанная ошибка. [link](https://github.com/Mika1212/HomeTar/blob/563c656f0938bbca5092d835bc927b144af58920/src/main/java/HomeTar.java#L135)
2. В отличие от языка С, в Java в качестве аргументов имя исполняемого файла не передаётся. [Про аргументы в Java](https://docs.oracle.com/javase/tutorial/essential/environment/cmdLineArgs.html). [link](https://github.com/Mika1212/HomeTar/blob/563c656f0938bbca5092d835bc927b144af58920/src/main/java/HomeTar.java#L19)

**Comment by Mika1212** [comment]
А имя исполняемого файла в джаве не передается не передается всегда? Или оно может или передаваться, или нет?

**Comment by Saloed** [comment]
Передаются только аргументы. Имя исполняемого файла не передаётся. Никогда.

**Comment by Mika1212** [comment]
Понял, тогда все готово
